### ISSUE TITLE
Error when extracting deployment transactions of the contracts

### ISSUE THREAD

**Issue by nicedinner** [eth-sri/ilf#20]
When i try to extracting deployment transactions use follow code.
$ rm example/crowdsale/transactions.json    # this line is good
$ python3 script/extract.py --proj example/crowdsale/ --port 8545     # this line cause the error

i run into follow error:
/home/cyma/.npm-global/lib/node_modules/truffle/build/4986.bundled.js:329
  const isREPL = options?.isREPL ?? false; //default to not displaying REPL commands
                         ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.__webpack_require__.f.require (/home/cyma/.npm-global/lib/node_modules/truffle/build/cli.bundled.js:608:28)
    at /home/cyma/.npm-global/lib/node_modules/truffle/build/cli.bundled.js:538:40
    at Array.reduce (<anonymous>)
/home/cyma/.npm-global/lib/node_modules/truffle/build/4986.bundled.js:329
  const isREPL = options?.isREPL ?? false; //default to not displaying REPL commands
                         ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.__webpack_require__.f.require (/home/cyma/.npm-global/lib/node_modules/truffle/build/cli.bundled.js:608:28)
    at /home/cyma/.npm-global/lib/node_modules/truffle/build/cli.bundled.js:538:40
    at Array.reduce (<anonymous>)
/home/cyma/.npm-global/lib/node_modules/truffle/build/4986.bundled.js:329
  const isREPL = options?.isREPL ?? false; //default to not displaying REPL commands
                         ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.__webpack_require__.f.require (/home/cyma/.npm-global/lib/node_modules/truffle/build/cli.bundled.js:608:28)
    at /home/cyma/.npm-global/lib/node_modules/truffle/build/cli.bundled.js:538:40
    at Array.reduce (<anonymous>)

By the way, i can fuzz the example successfully.  
$ python3 -m ilf --proj ./example/crowdsale/ --contract Crowdsale --fuzzer imitation --model ./model/ --limit 2000 #so, this line is good

**Comment by EgbertTtTt** [comment]
same questions

**Comment by LostBenjamin** [comment]
Hi @nicedinner and @EgbertTtTt,

Sorry for the delay.

These errors are caused by version mismatches. I have put the correct version in the Dockerfile and tested it from my side. Please update the Dockerfile and let me know if it works for you.

Best,
Jingxuan
